.github/shared-workflows/terraform_apply.yml
.github/shared-workflows/terraform_detect_drift.yml
.github/shared-workflows/terraform_lock.yml
.github/shared-workflows/terraform_plan.yml
.github/shared-workflows/terraform_unlock.yml

verbatim, from cd767251ee09d60db7596045a4f5637220f8ff0f

shared workflows, imported from tacos-gha.demo@cd76725

---

manual_tests/scenarios/draft_pr.py

Draft PR scenario is passing up until the merge step (final step)

Getting draft PR scenario nearly passing

---

.envrc

Fixing errors with getting slices to lock

Updating envrc

---

lib/getsentry-sac/sac-terraformer

blocks https://github.com/getsentry/tacos-gha.demo/pull/705

update sudo-gcp config format, one last time

---

.github/workflows/tacos_apply.yml
.github/workflows/tacos_detect_drift.yml
.github/workflows/tacos_lock.yml
.github/workflows/tacos_plan.yml
.github/workflows/tacos_unlock.yml
.gitignore
manual_tests/lib/gh/repo.py

- merged bukzor-sentryio to bukzor
- renamed tacos-demo to tacos-gha.demo

bukzor sentryio to bukzor

---

lib/tacos/dependent_slices.py
requirements-dev.in
requirements-dev.txt

see also: https://github.com/microsoft/pyright/issues/6976

upgrade pyright, ignore spurious error for now

---

.github/actions/setup/action.yml
.github/workflows/tacos_apply.yml
manual_tests/conftest.py
manual_tests/lib/gh/pr.py

The payload is cached on rerunning the job.

Switches to getting the draft status from gh instead of the payload.

---

.gitignore
lib/tf_lock/lib/env.sh
lib/tf_lock/release.py
lib/tf_lock/tf-lock
lib/tf_lock/tf-lock-acquire
lib/tf_lock/tf-lock-info
lib/tf_lock/tf-lock-release
lib/tf_lock/tf-state-info

tested and ready to merge AFAIK

tf-lock: update for "bare" terragrunt slice compat

---

.github/actions/setup/action.yml
.github/workflows/tacos_apply.yml
.github/workflows/tacos_detect_drift.yml
.github/workflows/tacos_plan.yml

it works: https://github.com/getsentry/tacos-gha.demo/actions/runs/7674024507/job/20917856803?pr=1014#step:4:2066

add ssh-key support

---

lib/tf_lock/acquire.py
lib/unix/tty-attach

- aggregate, organize, and update our todo items
- fix: allow for DEBUG unset
- fix(tf-lock-acquire): allow for "this make take some time" message

fix(tf-lock-acquire): allow for "this make take some time" message

---

TODO.md
lib/tf_lock/tf-lock-info

I wasnt able to reproduce the situation, but at least we'll see an AssertionError now, instead of waiting forever.

fix(tf-lock-info): prevent infinite regress

---

.github/workflows/tacos_apply.yml
TODO.md
lib/ci/github-pr-setenv
lib/ci/release-lock
lib/ci/tacos-apply
lib/github-actions/set-env
lib/github-actions/set-output
lib/github-actions/step-summary

I verified that the `apply` test continues to pass.

fix: approval is different than approvers: $GITHUB_PR_APPROVED

---

TODO.md
lib/github-actions/printenv

this was causing debug mode to explode

printenv to stderr

---

TODO.grep.md
TODO.md
doc/rationale.md
lib/tf_lock/lib/env.sh
lib/tf_lock/tf-lock-info
spec/behaviors/force_unlock_on_dirty.py
spec/behaviors/message_on_lock_failure.py
spec/behaviors/plan_on_push.py
spec/conftest.py
spec/lib/gh/pr.py
spec/lib/gh/up_to_date.py
spec/lib/slice.py
spec/lib/tacos_demo.py
spec/lib/tf.py
spec/scenarios/draft_pr.py
spec/scenarios/feature_branch_happy_path.py
spec/scenarios/lock_contention.py
spec/scenarios/separate_changes_dont_conflict.py

-  Slices.force_clean: force_unlock *before* switching to main branch
-  tf-lock-info: show output of tf-init on third, final try
-  need to tf-init during "first-time setup"
-  re-enable $DEBUG behavior in lib/tf_lock

fixes while running the test suite

---

TODO.grep.md
spec/lib/tf.py

this shouldn't be requesting "apply" permission anymore

fix(security): reduce permissions requested during tf-init

---

.github/actions/list-slices/action.yml

Fixing a typo in paths filter version.

Fixing paths filter version

---

README.md

Making it easier to find the install doc

Add link to install doc in readme

---

.github/actions/just-the-basics/action.yml
.github/actions/setup/action.yml
.github/workflows/tacos_apply.yml
lib/ci/bin/tf-step-summary
lib/ci/tacos_plan_summary.py
lib/ci/tacos_plan_summary_test.py

- **add url to tacos-plan summary**
- **update tests**

add hyperlinks to summary headers

---

TODO.grep.md
lib/ci/tacos_plan_summary_test.py
lib/make/venv

fixed the tests

---

lib/ci/bin/tf-step-summary
lib/ci/default-shell
lib/ci/tacos_summary.py
lib/ci/tacos_summary_test.py

For unknown reasons, the command added in #183 has (seemingly?) started failing.
This test adds some fail-soft behavior for that situation, and test coverage for the new code.

fix: "failed to get run"

---

.github/workflows/tacos_plan.yml
TODO.grep.md
lib/ci/bin/terragrunt-noninteractive
lib/ci/bin/tf-log-normalize
lib/github_actions/log-as-step-summary
lib/unix/quietly
lib/unix/uncolor

also: ensure logging is unbuffered

skip "quietly" behavior during debug

---

TODO.md
doc/TODONE.md

This is the result of a full read-through interactively with Neo.

TODO cleanup

---

lib/ci/github-pr-setenv

proof the fix works
https://github.com/getsentry/terraform-sandboxes.private/actions/runs/8837152901
proof before the fix it didn't work
https://github.com/getsentry/terraform-sandboxes.private/actions/runs/8821497079/job/24217492154

fix: or in jq is 'or'

---

lib/tf_lock/lib/env.sh

the debug logs are too verbose to the point where it is difficult to find useful output, increase the debug level

adjust debug level

---

lib/ci/tacos_summary.py
pyproject.toml
requirements-dev.in
requirements-dev.txt
spec/lib/tacos_demo.py
spec/lib/tacos_demo_test.py

We now put multiple slices into a single comment, so we have to do a bit different comment parsing.

Changes tests to account for changed comment format.

---

TODO.md
spec/conftest.py

refactored from #233 -- thanks!
i've set TENV_AUTO_INSTALL=true as suggested in filippo's error message, with CI in mind

fix(test): ensure tenv can find/install its binary cache

---

lib/ci/tacos_plan_summary.py

I think this should have a cookie to match what we have in the apply summary job

Add cookie 

---

.github/workflows/required_check.yml
lib/ci/github-pr-setenv
lib/ci/tacos-apply
lib/ci/tacos_summary.py
spec/lib/gh/pr.py
spec/lib/tacos_demo.py
spec/scenarios/required_checks_fail.py

tacos apply needs required checks to pass

feat: Tacos apply depends on required checks passing

---

lib/tf_lock/tf_lock_acquire.py
spec/lib/slice.py
spec/scenarios/orphaned_lock.py

This is a quick fix for the tacos unlock bug, it will check if a lock is attached to a closed/merged PR.

Bump Stable

---

.github/actions/setup/action.yml

This will allow us to log our terraform apply events to Datadog.

feat: install terraform logging tool

---

.github/actions/setup/action.yml

merge stable

---

.github/actions/just-the-basics/action.yml

It now supports a path parameter, so is suitable for use.

Switches back to fork source for direnv.

---

.github/actions/just-the-basics/action.yml

Integrating the base repo was proving difficult, so this is an updated version of our fork that includes the correct cache endpoints.

Bumps direnv dependency.
